### ISSUE TITLE
Issues: Need to fix ASAP

### ISSUE THREAD

**Issue by hansputera** [smantriplw/twibbon#1]
## High Priorities
- [ ] Support drag and drop on mobile devices (#2)
- [ ] Support photo cropping (#2)
- [ ] Fix zoom sensivity

**Solution:**
1. Maybe we can take a look to https://www.npmjs.com/package/cropperjs

## Medium Priorities
- [ ] Resize the canvas dimensions after use resize their window (#3)

## Low Priorities
- [ ] Reduce the build chunks size
